lab-cosmo/sphericart

.github/workflows/build-wheels.yml

Until we figure a way to handle torch version requirements on the wheels, we should only distribute sphericart-torch as source code.

Do not upload sphericart-torch wheels from CI

---

benchmarks/cpp/benchmark.cpp
sphericart/CMakeLists.txt
sphericart/include/macros.hpp
sphericart/include/templates.hpp

Otherwise the `float` version of the code ends up doing a lot of operations using `double`.

Cast litterals in macros to the same type as sph

---

.github/workflows/build-wheels.yml
.github/workflows/tests.yml
README.md
docs/src/installation.rst
setup.py
sphericart-torch/setup.py
sphericart/CMakeLists.txt

Use this when building wheels on CI to make sure the wheels will run on any system

Allow to disable -march=native from CMake

---

docs/src/maths.rst
sphericart/include/templates.hpp
sphericart/tests/CMakeLists.txt
sphericart/tests/test_hardcoding.cpp
sphericart/tests/test_samples.cpp

Fixes #39, which was due to the inconsistent order of parameters in `hardcoded_sph_sample`. 
Will also add a test for the consistency of array and sample calls so that this does not happen again, given that we don't use the direct sample calls that much.

Quickfix for hardcoded_sample

---

sphericart/include/macros.hpp
sphericart/include/sphericart.hpp
sphericart/include/templates.hpp
sphericart/src/sphericart.cpp
sphericart/tests/test_hardcoding.cpp
sphericart/tests/test_samples.cpp

In this PR I try to address some concerns on the fact that the C++ core is kind of impenetrable. I added throughout comments explaining what is done and why. Is there anything else that would be useful to do while I've all the C++ files open?

Improving the developer comments in the C++ implementation

---

sphericart-torch/python/tests/test_nn.py
sphericart-torch/src/autograd.cpp
sphericart-torch/src/cuda.cu

At the moment, we decide whether to calculate double backward second derivatives by checking if `ddsph` is defined or not. This is fine for the CPU code, but on the CUDA code `dsph` and `ddsph` are defined also if these are not required. This leads to second derivatives of the wrong shape which cause torch to crash later on

CUDA backward bug

---

benchmarks/jax/benchmark.py
examples/jax/example.py
sphericart-jax/python/sphericart/jax/ddsph.py
sphericart-jax/python/sphericart/jax/dsph.py
sphericart-jax/python/tests/test_transforms.py
sphericart-jax/src/jax.cpp

As the title says - the C++ class gets cached to avoid recomputing prefactors and allocating buffers

Added caching of the sphericart class

---

ci/docker/Dockerfile.build
ci/pipeline.yml

Once this is merged with main, any branch that builds on top of main should be able to trigger the CI with a new image with Python 3.10 in the environment

Updated CI to use an image with Python 3.10 installed

---

sphericart-torch/src/torch.cpp

Sphericart already uses `TORCH_LIBRARY` but when serializing the library reference into a TorchScript JIT module, the class needs a pickle/unpickle method as well.

Add pickling methods to support TorchScript.

---

CMakeLists.txt

This uses -O3 instead of -O2. In some cases, -O2 does not allow vectorization

Make "release" the default install configuration

---

sphericart-torch/CMakeLists.txt

Follow up to #95, the `sphericart_torch` needs to be defined before we can set its properties.

Don't set properties on sphericart_torch target before defining the target

---

.github/workflows/tests.yml
ci/docker/Dockerfile.base
ci/pipeline.yml
setup.py
sphericart-jax/setup.py
sphericart-torch/setup.py

We use cmake's `--parallel` flag to speed up compilation for Python builds

Parallelize compilation with cmake

---

ci/pipeline.yml

There appears to be issues with the filesystem that is making the pipeline build the environment again rather than load from cache. Raising the timeout limits to ensure that this doesn't cause the CI pipelines to fail due to timeouts.

Raise timeout limits

---

sphericart/include/sphericart_cuda.hpp
sphericart/src/cuda_base.cu
sphericart/src/sphericart_cuda.cu

This PR should fix allocating prefactors on every visible device, as well as broadcasting adjust_shared_memory onto every visible device.
In the compute code, it will determine the device that xyz is allocated on, and use the correct prefactor pointer as well as force a context switch to that device.

Multiple Devices Support

---

.clang-format

Remove MOPS leftover in `.clang-format`

---

sphericart/CMakeLists.txt

Simply changed `CUDA_ARCHITECTURES native` to `CUDA_ARCHITECTURES all` in sphericart/CMakeLists.txt. Should allow "offline" compilation.

Allow device compilation without GPU available #116

---

julia/test/python/test_python.py

The test is probably pulling Python from PyPI and therefore there was no CI failure even though the Python API was changed

Fix Julia/Python consistency test

---

benchmarks/jax/benchmark.py
benchmarks/pytorch/benchmark.py
benchmarks/pytorch/benchmark_second_derivatives.py

Benchmarks were left broken by the change in API for jax and pytorch. Now everything should be compatible.

Update benchmarks to new API

---

sphericart-torch/src/torch_cuda_wrapper.cpp

As `AT_DISPATCH_FLOATING_TYPES(x.type()`  pattern is deprecated since https://github.com/pytorch/pytorch/pull/17996

Use `.scalar_type()` in `AT_DISPATCH`

---

pyproject.toml
tox.ini

We should no longer need this.

Stop pinning numpy to <2.0

---

scripts/check-format.sh
scripts/format.sh
sphericart-torch/CMakeLists.txt
sphericart-torch/src/autograd.cpp
sphericart-torch/src/streams.cpp
sphericart-torch/src/torch_cuda_wrapper.cpp
sphericart/CMakeLists.txt

This should enable using the pre-built wheels with a CPU-only version of torch, by moving the dependency on `libtorch_cuda` from `sphericart_torch` to `sphericart_torch_cuda_stream`

Dynamically load `c10::cuda::getCurrentCUDAStream` in sphericart-torch

---

julia/Project.toml
julia/src/normalisations.jl
julia/test/test_f32.jl

There was a bug in the basis construction, now FloatX for arbitrary X should work, added tests for Float32 and Float128. (also good to test for numerical stability)

Allow FloatX for arbitary X

---

.github/workflows/docs.yml
.github/workflows/tests.yml
sphericart-jax/pyproject.toml
tox.ini

Ubuntu 20.04 is deprecated on GH actions, plus our tests were using a mix of 20.04 and 22.04, now it's all 22.04

Upgrade tests to Ubuntu 22.04

---

sphericart-torch/CMakeLists.txt
sphericart/include/cuda_cache.hpp
sphericart/include/dynamic_cuda.hpp

This PR fixes two things:
- when there is a cuda driver mismatch on the system vs. what sphericart has been compiled with. For example when the driver max supported toolkit is 12.4, but code has been compiled with 12.6. Fix here is to write cubin code with NVRTC directly, rather than writing PTX and having NVRTC attempt to jit-compile it to SASS.
- removed the cudnn hack so things work in write-disabled environments. Our wheels support at minimum pytorch 2.4 so I think this is fine.

CSCS Compatibility
