CMakeLists.txt, benchmarks/CMakeLists.txt, benchmarks/cpp/benchmark.cpp, benchmarks/pytorch/benchmark.py, examples/python/example.py, examples/pytorch/example.py, sphericart/tests/CMakeLists.txt, sphericart/tests/test_hardcoding.cpp
Added some benchmarks for CUDA so we know what we are doing. Also separated out the benchmark part from timings.cpp and renamed it to test_hardcoded given it does test the hardcoded part of the derivatives.
=> Tests and benchmarks

benchmarks/pytorch/benchmark.py
More flexible handling of the "warmup phase" in pytorch tests, to also check for anomalous fluctuations in timings
=> Verbose benchmarks

sphericart-torch/src/cuda.cu
fixed an issue with illegal memory accesses for small lmax.
Also significantly improves the small lmax timings as a consequence (but not higher lmax - this will be done in separate PR).
=> illegal memory access fix

sphericart-torch/include/sphericart/torch.hpp, sphericart-torch/src/autograd.cpp, sphericart-torch/src/cuda.cu
modified the CUDA code such that it uses additional threads whose only purpose (at the moment) is to write out the buffers to global memory with coalesced access.
=> improved global memory coalescing

sphericart-torch/src/cuda.cu
Resolved build errors that were reported by Ilyes
=> Remove unwanted }

sphericart-torch/include/sphericart/torch.hpp, sphericart-torch/python/tests/test_cuda.py, sphericart-torch/src/cuda.cu, sphericart/include/templates.hpp
An effort to clean-up and optimize the CUDA (and possibly CPU) implementation, reusing code whenever possible
A few action points, or at least points for discussion:
=> Clean-up CUDA implementation

sphericart-torch/python/sphericart/torch/__init__.py, sphericart-torch/python/tests/test_nn.py, sphericart-torch/src/autograd.cpp
Duplicate of #61 to try to un-glitch the CI. Solves #59.
=> Fix torch derivative bug

.readthedocs.yml, benchmarks/pytorch/benchmark_second_derivatives.py, docs/src/examples.rst, docs/src/jax-api.rst, docs/src/jax-examples.rst, examples/jax/example.py, examples/pytorch/example.py, sphericart-jax/python/sphericart/jax/ddsph.py, sphericart-jax/python/sphericart/jax/dsph.py, sphericart-jax/python/sphericart/jax/sph.py, sphericart-jax/python/sphericart/jax/spherical_harmonics.py, sphericart-jax/python/tests/pure_jax_sph.py, sphericart-jax/python/tests/test_autograd.py, sphericart-jax/python/tests/test_consistency.py, sphericart-jax/python/tests/test_nn.py, sphericart-jax/python/tests/test_precision.py, sphericart-jax/python/tests/test_pure_jax.py, sphericart-jax/python/tests/test_transforms.py, sphericart-jax/setup.py
At the moment, the sphericart.jax.spherical_harmonics function does not show up in the documentation
=> Try to fix documentation bug

docs/src/api.rst, docs/src/examples.rst, docs/src/index.rst, docs/src/installation.rst
This PR adds our preliminary Julia documentation to readthedocs, mainly as links to the Julia readme
=> Preliminary Julia docs

examples/pytorch/example.py
Torch example used the gradient of a quantity that is meant to be constant to check for consistent cpu/gpu results, leading to misleading results because the gradient is meant to be zero.
=> Fixed torch example

docs/requirements.txt, docs/src/conf.py, docs/src/installation.rst, docs/src/jax-examples.rst, docs/src/pytorch-api.rst, examples/cuda/example.cu, sphericart/CMakeLists.txt
Updates the documentation instructions regarding CUDA and JAX installations and switches the theme to furo
=> Documentation updates

.github/workflows/build-wheels.yml, setup.py
This is how we are already doing this for metatensor
=> Do not use local path for dependencies when build sdist for release

julia/Project.toml, julia/src/SpheriCart.jl, julia/src/api.jl, julia/src/spherical.jl
This change seems necessary to not rely on a "home-made" memory management tool.
=> Switch to Bumper for Managing Temporaries 

pyproject.toml, tox.ini
=> Pin numpy to < 2.0.0

pyproject.toml, python/tests/test_no_points.py, sphericart-jax/python/tests/test_no_points.py, sphericart-torch/python/tests/test_no_neighbours.py, sphericart-torch/python/tests/test_no_points.py, sphericart/src/sphericart.cpp, sphericart/src/sphericart_cuda.cu
This commit patches in support for zero-sized tensors for cases where there are no neighbours.
=> zero-neighbour patch

setup.py, sphericart-jax/setup.py, sphericart-torch/setup.py
=> fix to build system to limit number of threads #115

README.md, docs/src/examples.rst, docs/src/spherical-complex.rst, examples/python/complex.py, examples/python/spherical.py, examples/python/spherical_and_complex.py, tox.ini
As more requests are coming in for these two slightly different types of computation, it is appropriate to provide examples for these use cases
=> Provide examples for spherical coordinates and/or complex spherical harmonics

sphericart-jax/src/sphericart_jax_cpu.cpp, sphericart-jax/src/sphericart_jax_cuda.cu
In `main`, this code:
```
import jax
import sphericart.jax
key = jax.random.PRNGKey(0)
xyz = 6 * jax.random.normal(key, (100, 3))
function = sphericart.jax.spherical_harmonics
sph = function(xyz, l_max=3)
hessian = jax.hessian(lambda xyz: jax.numpy.sum(function(xyz, l_max=3)))(xyz)
grad = jax.grad(lambda xyz: jax.numpy.sum(function(xyz, l_max=3)))(xyz)
hessian = jax.hessian(lambda xyz: jax.numpy.sum(function(xyz, l_max=3)))(xyz)
sph = function(xyz, l_max=3)
sph = function(xyz, l_max=3)
```
creates 3 classes: one for sph, one for dsph, one for ddsph.
This PR fixes it
=> Cache only once in sphericart-jax

.github/workflows/build-jax-wheels.yml, .github/workflows/build-torch-wheels.yml, .github/workflows/build-wheels.yml
We also need to release these to PyPI.
=> Also build sdist on CI

docs/src/maths.rst, python/src/sphericart/spherical_harmonics.py
Just some docstring & doc cleaning
=> Correct typo and add explicit expression for solid harmonics prefactor

julia/Project.toml, julia/src/SpheriCart.jl, julia/src/api.jl, julia/src/batched_kernels.jl, julia/src/generated_kernels.jl, julia/src/ka_kernels.jl, julia/src/normalisations.jl, julia/src/spherical.jl, julia/test/test_ka.jl
- some tweaks to the internals to make GPU usage a bit easier
- replace OffsetArray for Flm with Array or SArray
- some additional interface functions
=> JL: Improve GPU Interface

.github/workflows/tests.yml, pyproject.toml, sphericart-jax/pyproject.toml, sphericart-torch/pyproject.toml
Otherwise setuptools will prevent installations on newer versions.
=> Update license fields and bump to Py3.9
